### ISSUE TITLE
Failed to activate the linter-just-say-no package

### ISSUE THREAD

**Issue by ghost** [lexicalunit/linter-just-say-no#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.9.5
**Thrown From**: [linter-just-say-no](https://github.com/lexicalunit/linter-just-say-no) package, v0.4.0
### Stack Trace

Failed to activate the linter-just-say-no package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.module.exports.activate (/Volumes/home/jm/Source/johnmuhl/dotfiles/atom/packages/linter-just-say-no/lib/init.coffee:68:33)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:46)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".DS_Store",
      ".git"
    ],
    "disabledPackages": [
      "metrics"
    ],
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "tomorrow-syntax"
    ]
  },
  "linter-just-say-no": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
block-cursor, v0.13.1
color-picker, v2.0.11
cursor-blink-interval, v0.3.1
file-icons, v1.6.9
language-fish-shell, v1.0.2
language-ini, v1.12.0
linter, v1.5.0
linter-htmlhint, v0.1.1
linter-js-standard, v3.1.0
linter-jsonlint, v0.1.4
linter-just-say-no, v0.4.0
linter-less, v2.1.0
linter-rubocop, v0.3.4
linter-write-good, v0.6.1
tomorrow-syntax, v0.2.0
weather, v0.14.1

# Dev
No dev packages
```

**Comment by lexicalunit** [comment]
Thanks for the report!
